### ISSUE TITLE
jezek/xgbutil does not exist

### ISSUE THREAD

**Issue by scrouthtv** [jezek/xgb#2]
https://github.com/jezek/xgb/blob/cec22bda1ce18b7a75cf028a67ad5f1c71a37831/examples/doc.go#L13-L14

Hello, in the documentation at the root of the examples folder, a package named `github.com/jezek/xgbutil` is mentioned. However, it does not exist: 

https://github.com/jezek/xgbutil

I'd recommend either reverting the link to BurntSushi/xgbutil or forking it to `jezek`

**Comment by jezek** [comment]
Hmm... When reverting the link and someone would use ```BurntSushi/xgbutil``` in project, then he wouldn't use ```jezek/xgb```, but ```BurntSushi/xgb```.

3 solutions come to my mind:
1) Change the doc link to BurntSushi with the note about dependecy.
2) Change the doc link & fill issue (make PR) to use ```jezek/xgb```.
3) Keep link & fork ```BurntSushi/xgbutil``` and change dependency.

@scrouthtv Which one would you recomend or do you have another idea?

**Comment by scrouthtv** [comment]
I'm in favor of 3)

As you said, xgbutil itself depends on xgb and Burnt sushi's xgbutil currently references their xgb not this one.

xgbutil seems unmaintained as well (it doesn't even have a go.mod) so forking it and reactivating would be a nice side-effect

**Comment by jezek** [comment]
I've forked it and rewrote dependencies needed to pass test/compile
