### ISSUE TITLE
/examples/shapes/main.go mentions Drawable function, but Drawable function isn't in the docs, only DrawableErrorNew

### ISSUE THREAD

**Issue by IoIxD** [jezek/xgb#5]

**Comment by jezek** [comment]
I think, you mean the line here:
https://github.com/jezek/xgb/blob/7a4fade77cf2a8406e63409d11ac844dfb150679/examples/shapes/main.go#L34

The xproto.Drawable is not a function, but [a Drawable type](https://github.com/jezek/xgb/blob/7a4fade77cf2a8406e63409d11ac844dfb150679/xproto/xproto.go#L1996). It is used in various ```xproto``` functions ([CreateGC](https://github.com/jezek/xgb/blob/7a4fade77cf2a8406e63409d11ac844dfb150679/xproto/xproto.go#L8201), [PolyLine](https://github.com/jezek/xgb/blob/7a4fade77cf2a8406e63409d11ac844dfb150679/xproto/xproto.go#L12176), [CopyArea](https://github.com/jezek/xgb/blob/7a4fade77cf2a8406e63409d11ac844dfb150679/xproto/xproto.go#L7816), ...) as an idicator of window where to draw (or do some drawing operation).

**Comment by IoIxD** [comment]
Ah, my bad.
